# Generated by Django 4.0.5 on 2022-07-02 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_recipe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Избран пользователями'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество просмотров'),
        ),
    ]
