version: "3.8"

services:
  nginx:
    build: ./nginx
    volumes:
      - media_files:/home/app/django-recipes/media
      - static_files:/home/app/django-recipes/static
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build: .
    command: gunicorn -w 4 Recipes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_files:/home/app/django-recipes/media
      - static_files:/home/app/django-recipes/static
    expose:
      - 8000
    env_file:
      - ./Recipes/.env
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Recipes/.env

volumes:
  postgres_data:
  media_files:
  static_files: